name: Continuous Integration

on:
  push:
    branches:
    - master

  pull_request:
    branches:
    - master

jobs:
  coverage:
    runs-on: ubuntu-24.04

    if: github.repository_owner == 'btmxh'

    steps:
    # This one weird trick speeds up every build! - @alxndrsn
    # see: https://github.com/actions/runner/issues/4030
    - name: Disable man-db dpkg trigger
      run: sudo apt-get remove --purge man-db

    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install LCov
      run: sudo apt-get update -q
        && sudo apt-get install lcov -q -y

    - name: Install dependencies
      run: |
        sudo apt-get install -y -q \
          mesa-vulkan-drivers \
          libwebp-dev \
          libavcodec-dev \
          libavformat-dev \
          libavutil-dev \
          libglfw3-dev

    - name: Install Vulkan SDK
      uses: jakoch/install-vulkan-sdk-action@v1
      with:
        optional_components: com.lunarg.vulkan.vma, com.lunarg.vulkan.volk
        install_runtime: true
        cache: true
        stripdown: true

        # TODO: test on both sw implementations?
        install_swiftshader: true
        # install_lavapipe: true

    - name: Configure
      run: cmake --preset=ci-coverage -Wno-error=dev

    - name: Build
      run: cmake --build build/coverage -j 2

    - name: Test
      working-directory: build/coverage
      run: ctest --output-on-failure --no-tests=error -j 2

    - name: Process coverage info
      run: cmake --build build/coverage -t coverage

    - name: Submit to codecov.io
      uses: codecov/codecov-action@v4
      with:
        file: build/coverage/coverage.info
        token: ${{ secrets.CODECOV_TOKEN }}

  sanitize:
    runs-on: ubuntu-24.04

    env:
      CC: clang-18
      CXX: clang++-18

    steps:
    - name: Disable man-db dpkg trigger
      run: sudo apt-get remove --purge man-db

    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install dependencies
      run: |
        sudo apt-get update -q &&
        sudo apt-get install -y -q \
          mesa-vulkan-drivers \
          libwebp-dev \
          libavcodec-dev \
          libavformat-dev \
          libavutil-dev \
          libglfw3-dev

    - name: Install Vulkan SDK
      uses: jakoch/install-vulkan-sdk-action@v1
      with:
        optional_components: com.lunarg.vulkan.vma, com.lunarg.vulkan.volk
        install_runtime: true
        cache: true
        stripdown: true

        # TODO: test on both sw implementations?
        install_swiftshader: true
        # install_lavapipe: true

    - name: Configure
      run: cmake --preset=ci-sanitize -Wno-error=dev

    - name: Build
      run: cmake --build build/sanitize -j 2

    - name: Test
      working-directory: build/sanitize
      env:
        ASAN_OPTIONS: "strict_string_checks=1:\
          detect_stack_use_after_return=1:\
          check_initialization_order=1:\
          strict_init_order=1:\
          detect_leaks=1:\
          halt_on_error=1"
        UBSAN_OPTIONS: "print_stacktrace=1:\
          halt_on_error=1"
      run: ctest --output-on-failure --no-tests=error -j 2

  test:
    strategy:
      matrix:
        os: [macos-14, ubuntu-24.04, windows-2022]

        type: [shared, static]

        include:
        - { type: shared, shared: YES }
        - { type: static, shared: NO }
        - os: ubuntu-24.04
          vcpkg_triplet: x64-linux-release
        - os: macos-14
          vcpkg_triplet: arm64-osx-release
        - os: windows-2022
          vcpkg_triplet: x64-windows-release

    runs-on: ${{ matrix.os }}

    steps:
    - name: Disable man-db dpkg trigger
      if: matrix.os == 'ubuntu-24.04'
      run: sudo apt-get remove --purge man-db

    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install static analyzers
      if: matrix.os == 'ubuntu-24.04'
      run: >
        sudo apt-get update -q
        && sudo apt-get install clang-tidy-18 cppcheck -y -q

        sudo update-alternatives --install
        /usr/bin/clang-tidy clang-tidy
        /usr/bin/clang-tidy-18 180

    - name: Install vcpkg build dependencies (MacOS)
      if: matrix.os == 'macos-14'
      run: brew install nasm

    - name: Install vcpkg build dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-24.04'
      run: sudo apt-get install nasm libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev pkg-config

    - name: Install system dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-24.04'
      run: sudo apt-get install mesa-vulkan-drivers

    - name: Install dependencies
      uses: johnwason/vcpkg-action@v7
      id: vcpkg
      with:
        pkgs: libwebp ffmpeg[x264,x265,vpx,mp3lame,opus,vorbis] glfw3
        triplet: ${{ matrix.vcpkg_triplet }}
        cache-key: ${{ matrix.os }}
        revision: master
        token: ${{ github.token }}

    - name: Install Vulkan SDK
      uses: jakoch/install-vulkan-sdk-action@v1
      with:
        optional_components: com.lunarg.vulkan.vma, com.lunarg.vulkan.volk
        install_runtime: true
        cache: true
        stripdown: true

        # TODO: test on both sw implementations?
        install_swiftshader: true
        # install_lavapipe: true

    - name: Register Vulkan ICD (Windows)
      if: matrix.os == 'windows-2022'
      shell: pwsh
      run: reg add "HKLM\SOFTWARE\Khronos\Vulkan\Drivers" /v "C:\Swiftshader\vk_swiftshader_icd.json" /t REG_DWORD /d 0 /f

    - name: Setup MultiToolTask
      if: matrix.os == 'windows-2022'
      run: |
        Add-Content "$env:GITHUB_ENV" 'UseMultiToolTask=true'
        Add-Content "$env:GITHUB_ENV" 'EnforceProcessCountAcrossBuilds=true'

    - name: Configure
      shell: bash
      run: |
        OS=${{ matrix.os }}
        cmake -Wno-error=dev \
          "--preset=ci-${OS%%-*}" \
          -D BUILD_SHARED_LIBS="${{ matrix.shared }}" \
          -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake \
          -DVCPKG_TARGET_TRIPLET=${{ matrix.vcpkg_triplet }} \
          -DVCPKG_MANIFEST_MODE=OFF

    - name: Setup PATH
      if: matrix.os == 'windows-2022' && matrix.type == 'shared'
      run: |
        Add-Content "$env:GITHUB_PATH" "$(Get-Location)\build\ci\libsve4_decode\Release"
        Add-Content "$env:GITHUB_PATH" "$(Get-Location)\build\ci\libsve4_log\Release"
        Add-Content "$env:GITHUB_PATH" "$(Get-Location)\build\ci\libsve4_utils\Release"

    - name: Build
      run: cmake --build build/ci --config Release -j 2

    - name: Install
      run: cmake --install build/ci --config Release --prefix prefix

    - name: Test
      working-directory: build/ci
      run: ctest --output-on-failure --no-tests=error -C Release -j 2

  docs:
    # Deploy docs only when builds succeed
    needs: [sanitize, test]

    runs-on: ubuntu-24.04

    if: github.ref == 'refs/heads/master'
      && github.event_name == 'push'
      && github.repository_owner == 'btmxh'

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - uses: actions/setup-python@v5
      with: { python-version: "3.12" }

    - name: Install m.css dependencies
      run: pip3 install jinja2 Pygments

    - name: Install Doxygen
      run: sudo apt-get update -q
        && sudo apt-get install doxygen -q -y

    - name: Build docs
      run: cmake "-DPROJECT_SOURCE_DIR=$PWD" "-DPROJECT_BINARY_DIR=$PWD/build"
        -P cmake/docs-ci.cmake

    - name: Deploy docs
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/docs/html
